dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "/docz"

# Any typos we should ignore?
excluded_words:
  - typoci
  - Plyr
  - npmrc
  - plyr
  - esw
  - seektime
  - iwatakeshi
  - svgr
  - plugin-proposal-nullish-coalescing-operator