/** Declaration file generated by dts-gen */

export const $$typeof: any;

export const defaultProps: {
    options: {
        controls: string[];
        i18n: {
            buffered: string;
            captions: string;
            currentTime: string;
            disableCaptions: string;
            download: string;
            duration: string;
            enableCaptions: string;
            enterFullscreen: string;
            exitFullscreen: string;
            fastForward: string;
            frameTitle: string;
            loop: string;
            menuBack: string;
            mute: string;
            normal: string;
            pause: string;
            play: string;
            played: string;
            quality: string;
            restart: string;
            rewind: string;
            seek: string;
            seekLabel: string;
            settings: string;
            speed: string;
            unmute: string;
            volume: string;
        };
    };
    source: {
        sources: {
            size: number;
            src: string;
            type: string;
        }[];
        type: string;
    };
};

export function compare(prev: any, next: any): any;

export function type(props: any): any;

